# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXr1sUMHh4lFXYwoThZAuhydWSU0IAkV
"""

candidatos_nombres = ["candidato1", "candidato2", "candidato3"]
votos_posibles = ["voto1", "voto2", "voto3"]
contador1 = 0
contador2 = 0
contador3 = 0
while True:
    voto_del_usuario = input("Ingrese el nombre del candidato por el que desea votar (ej. candidato1, candidato2, candidato3): ").lower()
    if voto_del_usuario == candidatos_nombres[0]:
        contador1 += 1
    elif voto_del_usuario == candidatos_nombres[1]:
        contador2 += 1
    elif voto_del_usuario == candidatos_nombres[2]:
        contador3 += 1
    else:
        print("Error: El voto ingresado no corresponde a ningún candidato válido.")
    continuar_votando = input("¿Desea ingresar otro voto? (s/n): ").lower()
    if continuar_votando != 's':
        break
print(f"Resultados parciales: {candidatos_nombres[0]}: {contador1}, {candidatos_nombres[1]}: {contador2}, {candidatos_nombres[2]}: {contador3}")
if contador1 > contador2 and contador1 > contador3:
    print("Ganador:", candidatos_nombres[0])
elif contador2 > contador1 and contador2 > contador3:
    print("Ganador:", candidatos_nombres[1])
elif contador3 > contador1 and contador3 > contador2:
    print("Ganador:", candidatos_nombres[2])
else:
    if contador1 == contador2 or contador1 == contador3 or contador2 == contador3:
        print("Empate: No hay un ganador único.")
    else:
        print("No se registraron votos suficientes o válidos para determinar un ganador.")
print("Gracias por su voto.")

import re

def validar_contraseña(contraseña):
    errores = []
    if len(contraseña) < 8:
        errores.append("La contraseña debe tener al menos 8 caracteres.")
    if not re.search(r"[A-Z]", contraseña):
        errores.append("La contraseña debe contener al menos una letra mayúscula.")
    if not re.search(r"[a-z]", contraseña):
        errores.append("La contraseña debe contener al menos una letra minúscula.")
    if not re.search(r"[0-9]", contraseña):
        errores.append("La contraseña debe contener al menos un número.")
    if not re.search(r"[!@#$%&*]", contraseña):
        errores.append("La contraseña debe contener al menos un carácter especial (!, @, #, $, %, &, *).")
    return errores

while True:
    contraseña = input("Ingrese una contraseña: ")
    mensajes_error = validar_contraseña(contraseña)
    if not mensajes_error:
        print("Contraseña válida. ¡Gracias!")
        break
    else:
        print("La contraseña no cumple los siguientes criterios:")
        for error in mensajes_error:
            print(f"- {error}")
        print("Por favor, inténtelo de nuevo.")