# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tp2gWo6TOojldkD-Lm7qItVnnPQ0gd3n
"""

lista_de_notas=[85,62, 70, 91, 55, 78, 45, 80, 72,68]
aprobados=0
reaprobados=0
for i in lista_de_notas:
    if i>=70:
        aprobados+=1
    else:
        reaprobados+=1
print(f"Cantidad de alumnos aprobados: {aprobados}")
print(f"Cantidad de alumnos reprobados: {reaprobados}")

lista_de_productos=["pan","huevos","leche","cereal"]
agotados=["leche"]
for item in agotados:
    if item in lista_de_productos:
        lista_de_productos.remove(item)
print(lista_de_productos)

contraseña_guardada = input("escriba su contraseña: ")
contraseña_ingresada = input("ingrese su contraseña: ")
while contraseña_ingresada != contraseña_guardada:
    print("contraseña incorrecta")
    contraseña_ingresada = input("ingrese su contraseña nuevamente: ")
print("contraseña correcta")

mixtos=[5, -2, 8, 0, -1, 10,-5]
positivos=[]
negativos=[]
for i in mixtos:
    if i>=0:
        positivos.append(i)
    else:
        negativos.append(i)
print(positivos)
print(negativos)