# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJkT613OEIuxtI-XXvrgb7BLuN5hPjNK
"""

d1={"nombre":"sara","edad":27,"documento":11111111}
print(d1)

#accede a un diccionario

#modificar diccionario
d1["nombre"]="laura"
print(d1)
d1["dirreccion"]="calle 123"
print (d1)

"""### Iterar y mostrar los valores de un diccionario

Hay varias formas de recorrer un diccionario y acceder a sus elementos:
"""

# Iterar sobre las claves (por defecto)
print("Iterando sobre las claves:")
for clave in d1:
    print(f"Clave: {clave}")

# Iterar sobre los valores
print("\nIterando sobre los valores:")
for valor in d1.values():
    print(f"Valor: {valor}")

# Iterar sobre los pares clave-valor (ítems)
print("\nIterando sobre clave-valor (ítems):")
for clave, valor in d1.items():
    print(f"Clave: {clave}, Valor: {valor}")

#diccionario
for i in d1:
    print(i)

for i in d1:
    print(i)

a1={"a":1,"b":2,"c":3}
a2={"a":1,"b":2,"f":3}
d={"a":a1,"b":a2}
print(d)

#dicciomario anidado
estudiantes={"Ana":("edad":27,"especialidad":"ING","promedio":3.8),"berto":("edad":20,"especialidad":"admin","promedio":4.0)}
print(estudiantes)
especialidad_ana=estudiantes["ana"]["especialidad"]
print("la especialidad de ana es:",especialidad_ana)
edad_beto=estudiantes["berto"]["edad"]
print("la edad de berto es:",edad_beto)
promedio_ana=estudiantes["ana"]["promedio"]
print("el promedio de ana es:",promedio_ana)

d={"a":1,"b":2}
print(d.get("a"))
it=d.items()
print(it)
print(list(it))
print(list(it)[0][1])

k=d.keys()
print(k)
print(list(k))
d.pop("a")
print (d)

#ejercicio
nombre = input("Ingrese su nombre: ")
edad_str = input("Ingrese su edad: ")
documento = float(input("Ingrese su documento: "))
usuario = {"nombre": nombre, "edad": edad, "documento": documento}
print("Nombre ingresado:", nombre)
print("Diccionario usuario:", usuario)
print(type(usuario))

preciosdefrutas={"platano":1.35,"manzana":0.80,"pera":0.85,"naranja":0.70}
fruta = input("ingrese la fruta:")
fruta_minuscula = fruta.lower()
if fruta_minuscula in preciosdefrutas:
    print(f"La fruta {fruta} está en el diccionario con un precio de {preciosdefrutas[fruta_minuscula]}.")
    if True:
     kilos=float(int((input("ingrese cuantos kilos quieres"))))
     precio=preciosdefrutas[fruta_minuscula]*kilos
     print("el precio de la fruta es:",precio)
else:
    print("La fruta {fruta} no está en el diccionario.")
    precio_ingresado = float(input(f"Ingrese el precio de {fruta}: "))
    preciosdefrutas[fruta_minuscula] = precio_ingresado
    print("Diccionario actualizado:", preciosdefrutas)